name: Build LaTeX Document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Create Release and Upload PDF
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
          tag_name: v${{ github.run_number }}
          name: Release "${{ github.event.head_commit.message }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}